### ISSUE TITLE
No route matches [GET] "/users/confirmation"

### ISSUE THREAD

**Issue by restot** [arty88/blog#1]
склонировал ваш проект просто запустил, видимо вы упустили этот момент с подтверждением учетной записи по почте, знаю что можно этот модуль просто отключить, но хотелось бы что бы он работал, и к сожалению я с гемом devise слабо знаком, если вам не составит труда это поправить, буду благодарен!

**Comment by artanikin** [comment]
@restot Для решения этой проблемы нужно добавить несколько полей в БД. 
Вариант 1: откатить миграцию создания таблицы **Users** и раскомментировать все поля связанные с **Confirmable**.
Вариант 2: создать новую миграцию и добавить необходимые поля, вместе с индексом. Я сделал правки в этом коммите: https://github.com/arty88/blog/commit/52cbf8872e45cdc7d88a0f7285cc4104ad82accf
А также необходимо в модели **User** добавить `:confirmable`
